name: chernogram
description: Chernogram — local media manager, social content studio and sharing tunnels
publish_to: 'none'
version: 0.5.0+5

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  http: ^1.5.0
  ota_update: ^7.1.0
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  photo_manager: ^3.10.0
  qr_flutter: ^4.1.0
  share_plus: ^10.1.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
