from pathlib import Path

path = Path('lib/update_service.dart')
text = path.read_text(encoding='utf-8')

old_expand = '''      await expandScript.writeAsString('''\nparam([string]$ZipPath, [string]$StagePath)\n$ErrorActionPreference = 'Stop'\nExpand-Archive -LiteralPath $ZipPath -DestinationPath $StagePath -Force\n''');\n'''
new_expand = '''      await expandScript.writeAsString('''\nparam([string]\\$ZipPath, [string]\\$StagePath)\n\\$ErrorActionPreference = 'Stop'\nExpand-Archive -LiteralPath \\$ZipPath -DestinationPath \\$StagePath -Force\n''');\n'''
if old_expand not in text:
    raise SystemExit('Expand PowerShell block not found')
text = text.replace(old_expand, new_expand, 1)

old_helper = '''      await helper.writeAsString('''\n$ErrorActionPreference = 'Stop'\n$pidToWait = $pid\n$source = ${quote(stage.path)}\n$dest = ${quote(installDir)}\n$exe = ${quote(exeName)}\n$log = ${quote(log)}\nfunction Log([string]$text) {\n  Add-Content -LiteralPath $log -Value ("[" + (Get-Date -Format s) + "] " + $text)\n}\ntry {\n  Log "Waiting for PID $pidToWait"\n  for ($i = 0; $i -lt 120; $i++) {\n    if (-not (Get-Process -Id $pidToWait -ErrorAction SilentlyContinue)) { break }\n    Start-Sleep -Milliseconds 250\n  }\n  if (Get-Process -Id $pidToWait -ErrorAction SilentlyContinue) {\n    throw "Old Chernogram process did not exit"\n  }\n  Log "Copying prepared update"\n  Get-ChildItem -LiteralPath $source -Force | ForEach-Object {\n    Copy-Item -LiteralPath $_.FullName -Destination $dest -Recurse -Force\n  }\n  $target = Join-Path $dest $exe\n  if (-not (Test-Path -LiteralPath $target)) {\n    throw "Updated executable was not copied"\n  }\n  Log "Starting updated Chernogram"\n  Start-Process -FilePath $target -WorkingDirectory $dest\n  Log "Update completed"\n} catch {\n  Log ("ERROR: " + $_.Exception.Message)\n  try {\n    Add-Type -AssemblyName PresentationFramework\n    [System.Windows.MessageBox]::Show(\n      "Не удалось завершить обновление Чернограма.`n`n" + $_.Exception.Message + "`n`nЖурнал: " + $log,\n      "Чернограм — обновление"\n    ) | Out-Null\n  } catch {}\n}\nStart-Sleep -Milliseconds 800\nRemove-Item -LiteralPath ${quote(tempRoot.path)} -Recurse -Force -ErrorAction SilentlyContinue\nRemove-Item -LiteralPath $PSCommandPath -Force -ErrorAction SilentlyContinue\n''');\n'''
new_helper = '''      await helper.writeAsString('''\n\\$ErrorActionPreference = 'Stop'\n\\$pidToWait = $pid\n\\$source = ${quote(stage.path)}\n\\$dest = ${quote(installDir)}\n\\$exe = ${quote(exeName)}\n\\$log = ${quote(log)}\nfunction Log([string]\\$text) {\n  Add-Content -LiteralPath \\$log -Value ("[" + (Get-Date -Format s) + "] " + \\$text)\n}\ntry {\n  Log "Waiting for PID \\$pidToWait"\n  for (\\$i = 0; \\$i -lt 120; \\$i++) {\n    if (-not (Get-Process -Id \\$pidToWait -ErrorAction SilentlyContinue)) { break }\n    Start-Sleep -Milliseconds 250\n  }\n  if (Get-Process -Id \\$pidToWait -ErrorAction SilentlyContinue) {\n    throw "Old Chernogram process did not exit"\n  }\n  Log "Copying prepared update"\n  Get-ChildItem -LiteralPath \\$source -Force | ForEach-Object {\n    Copy-Item -LiteralPath \\$_.FullName -Destination \\$dest -Recurse -Force\n  }\n  \\$target = Join-Path \\$dest \\$exe\n  if (-not (Test-Path -LiteralPath \\$target)) {\n    throw "Updated executable was not copied"\n  }\n  Log "Starting updated Chernogram"\n  Start-Process -FilePath \\$target -WorkingDirectory \\$dest\n  Log "Update completed"\n} catch {\n  Log ("ERROR: " + \\$_.Exception.Message)\n  try {\n    Add-Type -AssemblyName PresentationFramework\n    [System.Windows.MessageBox]::Show(\n      "Не удалось завершить обновление Чернограма.`n`n" + \\$_.Exception.Message + "`n`nЖурнал: " + \\$log,\n      "Чернограм — обновление"\n    ) | Out-Null\n  } catch {}\n}\nStart-Sleep -Milliseconds 800\nRemove-Item -LiteralPath ${quote(tempRoot.path)} -Recurse -Force -ErrorAction SilentlyContinue\nRemove-Item -LiteralPath \\$PSCommandPath -Force -ErrorAction SilentlyContinue\n''');\n'''
if old_helper not in text:
    raise SystemExit('Helper PowerShell block not found')
text = text.replace(old_helper, new_helper, 1)

path.write_text(text, encoding='utf-8')
print('Escaped PowerShell variables for Dart strings')
