from pathlib import Path


def replace(path: str, old: str, new: str) -> None:
    file = Path(path)
    source = file.read_text(encoding='utf-8')
    if old in source:
        file.write_text(source.replace(old, new), encoding='utf-8')


def main() -> None:
    # Repair the Dart interpolation generated by the feature patch.
    replace(
        'lib/internet_core.dart',
        "    final signature = '${signal['action']}|${signal['from']}|${signal['sdp']?.hashCode}|${signal['candidate']?.hashCode}';",
        '    final signature = "${signal[\'action\']}|${signal[\'from\']}|${signal[\'sdp\']?.hashCode}|${signal[\'candidate\']?.hashCode}";',
    )

    # Ignore signalling packets from a third participant in a direct call.
    replace(
        'lib/call_service.dart',
        """    if (sender.isEmpty || sender == _profileId) return;
    _adoptPeer(sender);
""",
        """    if (sender.isEmpty || sender == _profileId) return;
    if (_peerId != null && _peerId!.isNotEmpty && _peerId != sender) return;
    _adoptPeer(sender);
""",
    )

    # The brand palette exposes primary through the active theme.
    replace(
        'lib/chat_media.dart',
        'ChernogramColors.purple',
        'Theme.of(context).colorScheme.primary',
    )

    # camera/video_player geometry needs an explicit double.
    replace(
        'lib/chat_media.dart',
        """                            dimension: math.min(
                              MediaQuery.sizeOf(context).width - 34,
                              420,
                            ),
""",
        """                            dimension: math.min(
                              MediaQuery.sizeOf(context).width - 34,
                              420.0,
                            ).toDouble(),
""",
    )
    replace(
        'lib/chat_media.dart',
        """                            dimension: math.min(
                              MediaQuery.sizeOf(context).width - 36,
                              420,
                            ),
""",
        """                            dimension: math.min(
                              MediaQuery.sizeOf(context).width - 36,
                              420.0,
                            ).toDouble(),
""",
    )

    # Avoid optional image-format constraints that are not needed for recording.
    replace(
        'lib/chat_media.dart',
        """        enableAudio: true,
        imageFormatGroup: ImageFormatGroup.yuv420,
""",
        """        enableAudio: true,
""",
    )

    # Do not allow a locally purged attachment to be restored by relay history.
    replace(
        'lib/chat_media.dart',
        """    final raw = attachment.dataBase64;
    if (raw == null || raw.isEmpty) return null;
""",
        """    final raw = attachment.dataBase64;
    if (raw == null || raw.isEmpty) return null;
""",
    )

    print('Applied Chernogram 0.9 final compile and direct-call safeguards')


if __name__ == '__main__':
    main()
